This is the code examples found in a blog post about converting float to integer array ([https://www.marsja.se/how-to-convert-a-float-array-to-an-integer-array-in-python-with-numpy/](https://www.marsja.se/how-to-convert-a-float-array-to-an-integer-array-in-python-with-numpy/). 

In [1]:
import numpy as np


oned = np.array([0.1, 0.3, 0.4, 
                 0.6, -1.1, 0.3])

twod = np.array([[ 0.3,  1.2,  2.4,  3.1,  4.3],
       [ 5.9,  6.8,  7.6,  8.5,  9.2],
       [10.11, 11.1, 12.23, 13.2, 14.2],
       [15.2, 16.4, 17.1, 18.1, 19.1]])

In [2]:
display(oned)
display(oned.dtype)

array([ 0.1,  0.3,  0.4,  0.6, -1.1,  0.3])

dtype('float64')

## Converting a Float Array to Int
Here's how to convert the float array to an integer array:

In [3]:
# convert array to integer python
oned_int = oned.astype(int)
display(oned_int)
display(oned_int.dtype)

array([ 0,  0,  0,  0, -1,  0])

dtype('int32')

## 2-d Array
The same method, as above, can be applied to a n-way array. Here's how to do it on a 2-d array:

In [4]:
twod_int = twod.astype(int)
display(twod_int)
display(twod_int.dtype)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

dtype('int32')

## Rounding Before Converting
Here's how to round the numbers BEFORE converting the float numbers to integer:

In [5]:
oned = np.array([0.1, 0.3, 0.4, 
                 0.6, -1.1, 0.3])

oned = np.around(oned)

# numpy convert to int
oned_int = oned.astype(int)
display(oned_int)
display(oned_int.dtype)

array([ 0,  0,  0,  1, -1,  0])

dtype('int32')

## Ceil:

In [6]:
oned = np.array([0.1, 0.3, 0.4, 
                 0.6, -1.1, 0.3])

oned = np.ceil(oned)

# numpy float to int 
oned_int = oned.astype(int)
display(oned_int)
display(oned_int.dtype)

array([ 1,  1,  1,  1, -1,  1])

dtype('int32')

## Floor:

In [7]:
oned = np.array([0.1, 0.3, 0.4, 
                 0.6, -1.1, 0.3])

oned = np.floor(oned)

# numpy float to int 
oned_int = oned.astype(int)
display(oned_int)
display(oned_int.dtype)

array([ 0,  0,  0,  0, -2,  0])

dtype('int32')